Add Florentiner Recipe
lnnrtwttkhn/recipes pull request #56
Opened 2024-06-10 11:45 UTC by martinaengel

Maybe consider adding a Florentiner recipe. It is very delicious and great for Christmas season.

2024-06-13 09:09 UTC, lnnrtwttkhn commented on recipes/Florentiner.qmd
> +For the shortcrust dough:
Please add subheading, like this

```r
### For the shortcrust dough
```

2024-06-13 09:10 UTC, lnnrtwttkhn commented on recipes/Florentiner.qmd
> +- [175 g] soft butter
For all ingredients, please change to, e.g.,:

```r
- [ ] 175 g soft butter
```

The square brackets should be empty and only contain a space. In Markdown syntax, this then shows up as To-Do-List, like so:

- [ ] 175 g soft butter

2024-06-13 09:11 UTC, lnnrtwttkhn requested changes
Thanks for this PR @martinaengel! I've reviewed your PR and requested additional changes. Thank you!

2024-06-17 10:29 UTC, martinaengel commented
Thank you for the comments! I implemented them in the changes!

2024-06-18 09:23 UTC, lnnrtwttkhn commented on recipes/Florentiner.qmd
> +  - Vegetarian
Thank you @martinaengel for these additional changes! Would you you like to add your author name?
For this add your name to the author field in the YAMl header, like this:

```YAML
author: firstname lastname
```

2024-06-18 09:24 UTC, lnnrtwttkhn requested changes
Thank you for the additional changes @martinaengel! Do you want to add your author information.

2024-06-24 09:45 UTC, lnnrtwttkhn commented
Thanks again @martinaengel, I will merge this PR now!

2024-06-24 09:45 UTC, lnnrtwttkhn commented
@allcontributors please add @martinaengel for bug, content, code

2024-06-24 09:45 UTC, merged