Add carrot cake recipes
lnnrtwttkhn/recipes pull request #61
Opened 2024-06-10 12:25 UTC by sivanujah

Fixes #34

2024-06-13 09:18 UTC, lnnrtwttkhn commented on recipes/Vegan Carrot Cake.qmd
> +title: "Template for new recipe"
Please add a title, e.g., `Carrot Cake`.

2024-06-13 09:18 UTC, lnnrtwttkhn commented on recipes/Vegan Carrot Cake.qmd
> +image: "https://biancazapatka.com/en/moist-and-simple-carrot-cake-vegan/"
Please provide a URL to an image.

2024-06-13 09:19 UTC, lnnrtwttkhn commented on recipes/Vegan Carrot Cake.qmd
> +  - Add a list of catgeories here
Please add a few categories / tags, for your recipe, otherwise delete.

2024-06-13 09:19 UTC, lnnrtwttkhn commented on recipes/Vegan Carrot Cake.qmd
> +---
Please add your author information to the YAML header, using:

```yaml
author: <your name here>
```

2024-06-13 09:20 UTC, lnnrtwttkhn commented on recipes/Vegan Carrot Cake.qmd
> +- [ ] Add your ingredients here
Please remove this 

```
[ ] Add your ingredients here
```

2024-06-13 09:21 UTC, lnnrtwttkhn commented on recipes/Vegan Carrot Cake.qmd
> +- [1] 250g Carrots
Please remove the numbers from the To-Do List items. It should just contain a whitespace:

```r
- [ ] 250g Carrots
```

2024-06-13 09:21 UTC, lnnrtwttkhn commented on recipes/Vegan Carrot Cake.qmd
> +1. Fill tFill the batter into the prepared baking pan, smooth it out and bake on medium rack for 30-40 minutes.he batter into the prepared baking pan, smooth it out and bake on medium rack for 30-40
Please remove duplicate `Fill t`

2024-06-13 09:22 UTC, lnnrtwttkhn requested changes
Thank for the PR @sivanujah! I reviewed your PR and have requested additional changes. It would be great, if yo could take care of them. Thank you!

2024-06-14 12:18 UTC, sivanujah commented
Hello Lennart, thank you for your feedback! I changed my recipe according to your instructions. Please let me know, if you find something else that needs to be changed.

2024-06-17 11:41 UTC, lnnrtwttkhn commented
@allcontributors please add @sivanujah  for bug, content, code

2024-06-17 11:42 UTC, merged