Transfered potatoe recipe into the required structure
lnnrtwttkhn/recipes pull request #63
Opened 2024-06-10 12:33 UTC by Mirarufeger

Thanks for the review, this in the potatoe recipe in the updated structure.

2024-06-13 09:27 UTC, lnnrtwttkhn requested changes
Hi @Mirarufeger! Thank for this PR! I'm a bit confused, since there are two files in this PR. Could you please delete the one that is not needed? Thanks!

2024-06-17 10:38 UTC, Mirarufeger commented
Hi! I deleted the unnecessary file, everything should be alright now. :)

2024-06-18 10:00 UTC, lnnrtwttkhn commented on Potatoe recipe
> +  - carbs
Would you like to add your author information? Add it to the YAML header like this:

```YAML
author: firstname lastname
```

2024-06-18 10:03 UTC, lnnrtwttkhn requested changes
Thanks for this PR @Mirarufeger! Would you like to add your author information? See comment above.

Also, please move the file to the `/recipes` subfolder and rename to `potatoes.qmd`.

You can do this from the command line, executed from the root of the directory, like this:

```bash
mv "Potatoe recipes.qmd" recipes/ppotatoes.qmd
```

Thanks!

2024-06-24 09:48 UTC, lnnrtwttkhn commented
> Also, please move the file to the /recipes subfolder and rename to potatoes.qmd.

I just added this in https://github.com/lnnrtwttkhn/recipes/pull/63/commits/c1c6d0ed74807d8d384eb32b9c521b33d31c8d0f.

@Mirarufeger feel free to send another PR, if you still want to add your author information.

Ready to merge now! 🚀

2024-06-24 09:48 UTC, lnnrtwttkhn commented
@allcontributors please add @Mirarufeger  for bug, content, code

2024-06-24 09:48 UTC, merged