Added Poke Bowl Recipe
lnnrtwttkhn/recipes pull request #65
Opened 2024-06-11 06:57 UTC by sannaschrage

Hey, take a look into my new recipe. If you want, you can add it to your recipes :) Enjoy!

2024-06-13 09:32 UTC, lnnrtwttkhn commented on recipes/poke_bowl.qmd
> +title: "Poke Bowl with Tofu and Peanut Sauce"
Please add the separator for the YAML header:

```r
---
title:
image: 
....
---
```

2024-06-13 09:32 UTC, lnnrtwttkhn commented on recipes/poke_bowl.qmd
> +### Poke Bowl with Tofu and Peanut Sauce
This can be remove, since this is in the `title:` in the YAML header already.

2024-06-13 09:33 UTC, lnnrtwttkhn commented on recipes/poke_bowl.qmd
> +## two servings
I think this could be removed as well, or you only remove the heading indicators (i.e., the two `##`)

2024-06-13 09:33 UTC, lnnrtwttkhn commented on recipes/poke_bowl.qmd
> +### For the Poke Bowl:
Please add a newline after the heading.

2024-06-13 09:33 UTC, lnnrtwttkhn commented on recipes/poke_bowl.qmd
> +1.    Rinse the sushi rice under cold water until the water runs clear.
Please add a newline after the heading.

2024-06-13 09:34 UTC, lnnrtwttkhn commented on recipes/poke_bowl.qmd
> +### Prepare the Tofu:
Please add a newline after the heading.

2024-06-13 09:34 UTC, lnnrtwttkhn commented on recipes/poke_bowl.qmd
> +### Prepare the Rice:
Please add a newline after the heading.

2024-06-13 09:34 UTC, lnnrtwttkhn requested changes
Thank you @sannaschrage! Great PR, I've only requested a few minor changes. Could you please still add them? Thanks!

2024-06-17 10:29 UTC, sannaschrage commented
Hey, I just fixed the things you've given me feedback about. Maybe you want to take another look at it :)

2024-06-17 12:41 UTC, lnnrtwttkhn commented
Hey @sannaschrage, thank you for these additional changes! Looks perfect now! Would you still like to add your name to the author field in the YAML header? Like this:

```YAML
author: firstname lastname
```

2024-06-17 12:49 UTC, lnnrtwttkhn commented
Thanks @sannaschrage for the speedy addition!

> I just did, but in my feature branch. Can you update your main branch now (after you accepted the pull request) or do I need to create a new pull request?

That's perfect, I haven't merged your branch yet and the PR was automatically updated accordingly.

Ready to merge! 🚀

2024-06-17 12:49 UTC, lnnrtwttkhn commented
@allcontributors please add @sannaschrage for bug, content, code

2024-06-17 12:50 UTC, merged